import Layout from "./Layout";

import Components from "@components";

const Home = () => {
    return (
        <Layout title="Classes">
            <p>LA</p>
            <Components.Table heads={["test"]} pagination>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut2</td>
                </tr>
                <tr>
                    <td>Salut3</td>
                </tr>
                <tr>
                    <td>Salut4</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut5</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut7</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut9</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut7</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
                <tr>
                    <td>Salut</td>
                </tr>
            </Components.Table>
        </Layout>
    );
};

export default Home;
